export const config = {

  copyableComponents: [
    "assignment",
    "border",
    "content-body",
    "dd",
    "dl",
    "dt",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "h5p-container",
    "li",
    "ol",
    "panopto-container",
    "paragraph",
    "table",
    "tab-group",
    "th",
    "tbody-tr",
    "td",
    "ul",
    "vocab-cards",
    "vocab-item",
    "vocab-list",
    "vocab-wrapper",
    "youtube-container",
    "image-gallery",
    "image-box",
    "accordion-item",
    "columns",
    "col-item",
  ],
  unselectableComponents: [
    "add-accordion-btn",
    "add-assignment-btn",
    "add-content-body-btn",
    "add-dl-btn",
    "add-flip-card-btn",
    "add-img-btn",
    "add-vocab-btn",
    "add-vocab-card-btn",
    "one-column-layout",
    "two-column-layout",
    "content-wrapper",
    "card-body",
    "card-img",
    "footer",
    "footer-info",
    "footnotes",
    "side-by-side-item",
    "toggle-footnotes",
    "gallery-wrapper",
    "add-tab-btn",
    "add-col-item-btn",
  ],
  requiresJsComponents: [
    "table",
  ],
};

