export const config = {
  
  copyableComponents: [
    "assignment", 
    "border", 
    "content-body", 
    "dd",
    "dl", 
    "dt", 
    "h2", 
    "h3", 
    "h4", 
    "h5", 
    "h6", 
    "h5p-container",
    "li",
    "ol", 
    "panopto-container", 
    "paragraph", 
    "table",
    "th",
    "tbody-tr",
    "td",
    "ul", 
    "vocab-cards",
    "vocab-item",
    "youtube-container",
    "image-gallery",
    "image-box",
    "accordion-item",
  ],
  unselectableComponents: [
    "one-column-layout", 
    "two-column-layout", 
    "content-wrapper", 
    "card-body",
    "card-img",
    "description-term",
    "description-definition",
    "footer",
    "footer-info",
    "footnotes",
    "side-by-side-item",
    "toggle-footnotes",
    "gallery-wrapper",
  ],
  requiresJsComponents: [
    "image-gallery",
    "tabs",
    "youtube-container",
  ],
};

